WebUI/Controllers/CitasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class CitasController : Controller
    {
        // GET: Citas
        public ActionResult CitasLaboratorio()
        {
            return View();
        }
        public ActionResult Proximas()
        {
            return View();
        }
        public ActionResult AgendarCita()
        {
            return View();
        }
        public ActionResult ReAgendarCita()
        {
            return View();
        }
       
        public ActionResult Anteriores()
        {
            return View();
        }
    }
}

WebUI/Controllers/CuponesController.cs
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class CuponesController : Controller
    {
        public ActionResult Registrar()
        {
            return View();
        }
        public ActionResult ListarCupones()
        {
            return View();
        }

        public ActionResult EditarCupon()
        {
            return View();
        }
    }
}

WebUI/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class RolesController : Controller
    {
        public ActionResult RegistrarRolLaboratorio()
        {
            return View();
        }
        public ActionResult RegistrarRolAdmin()
        {
            return View();
        }
        public ActionResult ListarRolesAdmin()
        {
            return View();
        }
        public ActionResult ListarRolesProveedor()
        {
            return View();
        }
        public ActionResult EditarRolProveedor()
        {
            return View();
        }
        public ActionResult EditarRolAdmin()
        {
            return View();
        }
    }
}

WebUI/Controllers/SedesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class SedesController : Controller
    {
        public ActionResult Registrar()
        {
            return View();
        }
        public ActionResult ListarSedes()
        {
            return View();
        }
        public ActionResult EditarSede()
        {
            return View();
        }
    }
}

WebUI/Views/Shared/Layouts/DashboardAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />

    <link href="~/Content/css/Icons.css" rel="stylesheet" />
    <link href="~/Content/css/Plugins.css" rel="stylesheet" />
    <link href="~/Content/css/VicodinComponents.css" rel="stylesheet" />
    <link href="~/Content/css/VicodinResponsive.css" rel="stylesheet" />

    <link href="~/Content/CssDashboard/iconly.css" rel="stylesheet" />
    <link href="~/Content/CssDashboard/dashboard.css" rel="stylesheet" />
    <link href="~/Content/CssDashboard/Dashboard1.css" rel="stylesheet" />

    @Scripts.Render("~/bundles/jquery")

    <script src="~/Scripts/PluginsVicodinComponents.js"></script>
    <script src="~/Scripts/MainVicodinComponents.js"></script>

    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.12.1/b-2.2.3/datatables.min.js"></script>

    @Scripts.Render("~/bundles/ControlAcciones")

</head>
<body>
    <section style=" position: relative; z-index: 1;">
        <header class="ltn__header-area ltn__header-3  ">
            <!-- TOP HEADER -->
            <!-- Links de las paginas -->

            <div class="header-bottom-area ltn__border-top ltn__header-sticky  ltn__sticky-bg-white--- ltn__sticky-bg-secondary ltn__secondary-bg section-bg-1 menu-color-white d-none d-lg-block">
                <div class="container">
                    <div class="row">
                        <div class="col header-menu-column justify-content-center">
                            <div class="sticky-logo">
                            </div>
                            <div class="header-menu header-menu-2">
                                <nav>
                                    <div class="ltn__main-menu">
                                        <ul>
                                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                            <li>@Html.ActionLink("Nuestro Producto", "Producto", "Home")</li>
                                            <li>@Html.ActionLink("Laboratorios registrados", "Index", "Laboratorio")</li>
                                            <li>@Html.ActionLink("Contacto", "Index", "Contactanos")</li>
                                        </ul>
                                    </div>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    </section>
    <section class="app">
        <div id="sidebar" class="active">
            <div class="sidebar-wrapper active">
                <div class="sidebar-header position-relative">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="logo">
                            <a>
                                <img src="~/Assets/img/LogoNoLimits.png" alt="" srcset="">
                            </a>
                        </div>
                        <div class="theme-toggle d-flex gap-2  align-items-center mt-2" style="display:none !important;">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--system-uicons" width="20" height="20" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M10.5 14.5c2.219 0 4-1.763 4-3.982a4.003 4.003 0 0 0-4-4.018c-2.219 0-4 1.781-4 4c0 2.219 1.781 4 4 4zM4.136 4.136L5.55 5.55m9.9 9.9l1.414 1.414M1.5 10.5h2m14 0h2M4.135 16.863L5.55 15.45m9.899-9.9l1.414-1.415M10.5 19.5v-2m0-14v-2" opacity=".3"></path><g transform="translate(-210 -1)"><path d="M220.5 2.5v2m6.5.5l-1.5 1.5"></path><circle cx="220.5" cy="11.5" r="4"></circle><path d="m214 5l1.5 1.5m5 14v-2m6.5-.5l-1.5-1.5M214 18l1.5-1.5m-4-5h2m14 0h2"></path></g></g></svg>
                            <div class="form-check form-switch fs-6">
                                <input class="form-check-input  me-0" type="checkbox" id="toggle-dark">
                                <label class="form-check-label"></label>
                            </div>
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--mdi" width="20" height="20" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="m17.75 4.09l-2.53 1.94l.91 3.06l-2.63-1.81l-2.63 1.81l.91-3.06l-2.53-1.94L12.44 4l1.06-3l1.06 3l3.19.09m3.5 6.91l-1.64 1.25l.59 1.98l-1.7-1.17l-1.7 1.17l.59-1.98L15.75 11l2.06-.05L18.5 9l.69 1.95l2.06.05m-2.28 4.95c.83-.08 1.72 1.1 1.19 1.85c-.32.45-.66.87-1.08 1.27C15.17 23 8.84 23 4.94 19.07c-3.91-3.9-3.91-10.24 0-14.14c.4-.4.82-.76 1.27-1.08c.75-.53 1.93.36 1.85 1.19c-.27 2.86.69 5.83 2.89 8.02a9.96 9.96 0 0 0 8.02 2.89m-1.64 2.02a12.08 12.08 0 0 1-7.8-3.47c-2.17-2.19-3.33-5-3.49-7.82c-2.81 3.14-2.7 7.96.31 10.98c3.02 3.01 7.84 3.12 10.98.31Z"></path></svg>
                        </div>
                        <div class="sidebar-toggler  x">
                            <a href="#" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
                        </div>
                    </div>
                </div>
                <div class="sidebar-menu">
                    <ul class="menu">

                        <li class="sidebar-title">Menu</li>
                        <li class="sidebar-item active ">
                            <a href="/Administrador/Dashboard" class='sidebar-link'>
                                <i class="fas fa-columns"></i>
                                <span>Dashboard Admin</span>
                            </a>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a href="#" class='sidebar-link'>
                                <i class="fas fa-user-cog"></i>
                                <span>Roles</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    @Html.ActionLink("Registrar rol", "RegistrarRolAdmin", "Roles")
                                </li>
                                <li class="submenu-item ">
                                    @Html.ActionLink("Listar roles", "ListarRolesAdmin", "Roles")
                                </li>
                            </ul>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a href="#" class='sidebar-link'>
                                <i class="fas fa-user-plus"></i>
                                <span>Usuarios</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    @Html.ActionLink("Registrar Usuario", "RegistrarColabAdmin", "Colaboradores")
                                </li>
                                <li class="submenu-item ">
                                    @Html.ActionLink("Listar usuarios", "ListarColabAdmin", "Colaboradores")
                                </li>
                            </ul>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a href="#" class='sidebar-link'>
                                <i class="fas fa-server"></i>
                                <span>Sistema</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    @Html.ActionLink("Actualizar perfil", "ActualizarAdministrador", "Administrador")
                                </li>
                                <li class="submenu-item ">
                                    @Html.ActionLink("Precio membresia", "Membresia", "Sistema")
                                </li>
                                <li class="submenu-item ">
                                    @Html.ActionLink("Monto IVA", "Iva", "Sistema")
                                </li>
                            </ul>
                        </li>
                        <li class="sidebar-item active">
                            <a href="@Url.Action("Index", "Home", new { itemId = 1 })" class="sidebar-link">
                                <i class="fas fa-door-open m-lg-1"></i>
                                <span>Volver Al Inicio</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="position-relative" id="main">
            @RenderBody()
        </div>
    </section>
    <script src="~/Scripts/dashboard.js"></script>
</body>
</html>

WebUI/Views/Shared/Layouts/DashboardPaciente.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />

    <link href="~/Content/css/Icons.css" rel="stylesheet" />
    <link href="~/Content/css/Plugins.css" rel="stylesheet" />
    <link href="~/Content/css/VicodinComponents.css" rel="stylesheet" />
    <link href="~/Content/css/VicodinResponsive.css" rel="stylesheet" />

    <link href="~/Content/CssDashboard/iconly.css" rel="stylesheet" />
    <link href="~/Content/CssDashboard/dashboard.css" rel="stylesheet" />
    <link href="~/Content/CssDashboard/Dashboard1.css" rel="stylesheet" />

    <script src="~/Scripts/PluginsVicodinComponents.js"></script>
    <script src="~/Scripts/MainVicodinComponents.js"></script>

    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.12.1/b-2.2.3/datatables.min.js"></script>

    @Scripts.Render("~/bundles/ControlAcciones")

</head>
<body>
    <section style=" position: relative; z-index: 1;">
        <header class="ltn__header-area ltn__header-3  ">
            <!-- TOP HEADER -->
            <!-- Links de las paginas -->

            <div class="header-bottom-area ltn__border-top ltn__header-sticky  ltn__sticky-bg-white--- ltn__sticky-bg-secondary ltn__secondary-bg section-bg-1 menu-color-white d-none d-lg-block">
                <div class="container">
                    <div class="row">
                        <div class="col header-menu-column justify-content-center">
                            <div class="sticky-logo">
                            </div>
                            <div class="header-menu header-menu-2">
                                <nav>
                                    <div class="ltn__main-menu">
                                        <ul>
                                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                            <li>@Html.ActionLink("Nuestro Producto", "Producto", "Home")</li>
                                            <li>@Html.ActionLink("Laboratorios registrados", "Index", "Laboratorio")</li>
                                            <li>@Html.ActionLink("Contacto", "Index", "Contactanos")</li>
                                        </ul>
                                    </div>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    </section>
    <section class="app">
        <div id="sidebar" class="active">
            <div class="sidebar-wrapper active">
                <div class="sidebar-header position-relative">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="logo">
                            <a>
                                <img src="~/Assets/img/LogoNoLimits.png" alt="" srcset="">
                            </a>
                        </div>
                        <div class="theme-toggle d-flex gap-2  align-items-center mt-2" style="display:none !important;">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--system-uicons" width="20" height="20" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M10.5 14.5c2.219 0 4-1.763 4-3.982a4.003 4.003 0 0 0-4-4.018c-2.219 0-4 1.781-4 4c0 2.219 1.781 4 4 4zM4.136 4.136L5.55 5.55m9.9 9.9l1.414 1.414M1.5 10.5h2m14 0h2M4.135 16.863L5.55 15.45m9.899-9.9l1.414-1.415M10.5 19.5v-2m0-14v-2" opacity=".3"></path><g transform="translate(-210 -1)"><path d="M220.5 2.5v2m6.5.5l-1.5 1.5"></path><circle cx="220.5" cy="11.5" r="4"></circle><path d="m214 5l1.5 1.5m5 14v-2m6.5-.5l-1.5-1.5M214 18l1.5-1.5m-4-5h2m14 0h2"></path></g></g></svg>
                            <div class="form-check form-switch fs-6">
                                <input class="form-check-input  me-0" type="checkbox" id="toggle-dark">
                                <label class="form-check-label"></label>
                            </div>
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--mdi" width="20" height="20" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="m17.75 4.09l-2.53 1.94l.91 3.06l-2.63-1.81l-2.63 1.81l.91-3.06l-2.53-1.94L12.44 4l1.06-3l1.06 3l3.19.09m3.5 6.91l-1.64 1.25l.59 1.98l-1.7-1.17l-1.7 1.17l.59-1.98L15.75 11l2.06-.05L18.5 9l.69 1.95l2.06.05m-2.28 4.95c.83-.08 1.72 1.1 1.19 1.85c-.32.45-.66.87-1.08 1.27C15.17 23 8.84 23 4.94 19.07c-3.91-3.9-3.91-10.24 0-14.14c.4-.4.82-.76 1.27-1.08c.75-.53 1.93.36 1.85 1.19c-.27 2.86.69 5.83 2.89 8.02a9.96 9.96 0 0 0 8.02 2.89m-1.64 2.02a12.08 12.08 0 0 1-7.8-3.47c-2.17-2.19-3.33-5-3.49-7.82c-2.81 3.14-2.7 7.96.31 10.98c3.02 3.01 7.84 3.12 10.98.31Z"></path></svg>
                        </div>
                        <div class="sidebar-toggler  x">
                            <a class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
                        </div>
                    </div>
                </div>
                <div class="sidebar-menu">
                    <ul class="menu">
                        <li class="sidebar-title">Menu</li>
                        <li class="sidebar-item active ">
                            <a href="/Paciente/Dashboard" class='sidebar-link'>
                                <i class="fas fa-columns"></i>
                                <span>Dashboard Paciente</span>
                            </a>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a class='sidebar-link'>
                                <i class="fas fa-calendar-check"></i>
                                <span>Citas</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    @Html.ActionLink("Agendar Citas", "AgendarCita", "Citas")
                                </li>
                                <li class="submenu-item ">
                                    @Html.ActionLink("Re-agendar Citas", "ReAgendarCita", "Citas")
                                </li>
                            </ul>
                        </li>
                        <li class="sidebar-item ">
                            <span class='sidebar-link'>
                                <i class="fas fa-file-invoice-dollar m-lg-1"></i>
                                @Html.ActionLink("Facturas", "Facturas", "Paciente")
                            </span>
                        </li>
                        <li class="sidebar-item ">
                            <span class='sidebar-link'>
                                <i class="fas fa-file-invoice-dollar m-lg-1"></i>
                                @Html.ActionLink("Actualizar perfil", "ActualizarUsuario", "Paciente")
                            </span>
                        </li>
                        <li class="sidebar-item active">
                            <a href="@Url.Action("Index", "Home", new { itemId = 1 })" class="sidebar-link">
                                <i class="fas fa-door-open m-lg-1"></i>
                                <span>Volver Al Inicio</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
    </section>

    <script src="~/Scripts/dashboard.js"></script>
</body>
</html>

WebUI/Views/Shared/Layouts/DashboardProveedor.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />

    <link href="~/Content/css/Icons.css" rel="stylesheet" />
    <link href="~/Content/css/Plugins.css" rel="stylesheet" />
    <link href="~/Content/css/VicodinComponents.css" rel="stylesheet" />
    <link href="~/Content/css/VicodinResponsive.css" rel="stylesheet" />

    <link href="~/Content/CssDashboard/iconly.css" rel="stylesheet" />
    <link href="~/Content/CssDashboard/dashboard.css" rel="stylesheet" />
    <link href="~/Content/CssDashboard/Dashboard1.css" rel="stylesheet" />

    @Scripts.Render("~/bundles/jquery")


    <script src="~/Scripts/PluginsVicodinComponents.js"></script>
    <script src="~/Scripts/MainVicodinComponents.js"></script>


    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.12.1/b-2.2.3/datatables.min.js"></script>

    @Scripts.Render("~/bundles/ControlAcciones")

</head>
<body>
    <section>
        <header style=" position: relative; z-index: 1;" class="ltn__header-area ltn__header-3  ">
            <!-- TOP HEADER -->
            <!-- Links de las paginas -->

            <div class="header-bottom-area ltn__border-top ltn__header-sticky  ltn__sticky-bg-white--- ltn__sticky-bg-secondary ltn__secondary-bg section-bg-1 menu-color-white d-none d-lg-block">
                <div class="container">
                    <div class="row">
                        <div class="col header-menu-column justify-content-center">
                            <div class="sticky-logo">
                            </div>
                            <div class="header-menu header-menu-2">
                                <nav>
                                    <div class="ltn__main-menu">
                                        <ul>
                                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                            <li>@Html.ActionLink("Nuestro Producto", "Producto", "Home")</li>
                                            <li>@Html.ActionLink("Laboratorios registrados", "Index", "Laboratorio")</li>
                                            <li>@Html.ActionLink("Contacto", "Index", "Contactanos")</li>
                                        </ul>
                                    </div>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    </section>
    <section class="app">
        <div id="sidebar" class="active">
            <div class="sidebar-wrapper active">
                <div class="sidebar-header position-relative">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="logo">
                            <a>
                                <img src="~/Assets/img/LogoNoLimits.png" alt="" srcset="">
                            </a>
                        </div>
                        <div class="theme-toggle d-flex gap-2  align-items-center mt-2" style="display:none !important;">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--system-uicons" width="20" height="20" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M10.5 14.5c2.219 0 4-1.763 4-3.982a4.003 4.003 0 0 0-4-4.018c-2.219 0-4 1.781-4 4c0 2.219 1.781 4 4 4zM4.136 4.136L5.55 5.55m9.9 9.9l1.414 1.414M1.5 10.5h2m14 0h2M4.135 16.863L5.55 15.45m9.899-9.9l1.414-1.415M10.5 19.5v-2m0-14v-2" opacity=".3"></path><g transform="translate(-210 -1)"><path d="M220.5 2.5v2m6.5.5l-1.5 1.5"></path><circle cx="220.5" cy="11.5" r="4"></circle><path d="m214 5l1.5 1.5m5 14v-2m6.5-.5l-1.5-1.5M214 18l1.5-1.5m-4-5h2m14 0h2"></path></g></g></svg>
                            <div class="form-check form-switch fs-6">
                                <input class="form-check-input  me-0" type="checkbox" id="toggle-dark">
                                <label class="form-check-label"></label>
                            </div>
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--mdi" width="20" height="20" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="m17.75 4.09l-2.53 1.94l.91 3.06l-2.63-1.81l-2.63 1.81l.91-3.06l-2.53-1.94L12.44 4l1.06-3l1.06 3l3.19.09m3.5 6.91l-1.64 1.25l.59 1.98l-1.7-1.17l-1.7 1.17l.59-1.98L15.75 11l2.06-.05L18.5 9l.69 1.95l2.06.05m-2.28 4.95c.83-.08 1.72 1.1 1.19 1.85c-.32.45-.66.87-1.08 1.27C15.17 23 8.84 23 4.94 19.07c-3.91-3.9-3.91-10.24 0-14.14c.4-.4.82-.76 1.27-1.08c.75-.53 1.93.36 1.85 1.19c-.27 2.86.69 5.83 2.89 8.02a9.96 9.96 0 0 0 8.02 2.89m-1.64 2.02a12.08 12.08 0 0 1-7.8-3.47c-2.17-2.19-3.33-5-3.49-7.82c-2.81 3.14-2.7 7.96.31 10.98c3.02 3.01 7.84 3.12 10.98.31Z"></path></svg>
                        </div>
                        <div class="sidebar-toggler  x">
                            <a class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
                        </div>
                    </div>
                </div>
                <div class="sidebar-menu">
                    <ul class="menu">
                        <li class="sidebar-title">Menu</li>
                        <li class="sidebar-item active ">
                            <a href="/Laboratorio/Dashboard" class='sidebar-link'>
                                <i class="fas fa-columns"></i>
                                <span>Dashboard Proveedor</span>
                            </a>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a class='sidebar-link'>
                                <i class="fas fa-user-cog"></i>
                                <span>Roles</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    @Html.ActionLink("Registrar rol", "RegistrarRolLaboratorio", "Roles")
                                </li>
                                <li class="submenu-item ">
                                    @Html.ActionLink("Listar roles", "ListarRolesProveedor", "Roles")
                                </li>
                            </ul>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a class='sidebar-link'>
                                <i class="fas fa-user-nurse"></i>
                                <span>Colaboradores</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    @Html.ActionLink("Registrar Colaborador", "RegistrarColabProveedor", "Colaboradores")
                                </li>
                                <li class="submenu-item ">
                                    @Html.ActionLink("Listar Colaboradores", "ListarColabProveedor", "Colaboradores")
                                </li>
                            </ul>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a class='sidebar-link'>
                                <i class="fas fa-hospital"></i>
                                <span>Sedes</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    @Html.ActionLink("Registrar sedes", "Registrar", "Sedes")
                                </li>
                                <li class="submenu-item ">
                                    @Html.ActionLink("Listar sedes", "ListarSedes", "Sedes")
                                </li>
                            </ul>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a class='sidebar-link'>
                                <i class="fas fa-vial"></i>
                                <span>Examenes</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    @Html.ActionLink("Registrar examenes", "Registrar", "Examenes")
                                </li>
                                <li class="submenu-item ">
                                    @Html.ActionLink("Listar examenes", "Listar", "Examenes")
                                </li>

                            </ul>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a class='sidebar-link'>
                                <i class="fas fa-percentage"></i>
                                <span>Cupones</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    @Html.ActionLink("Registrar cupones", "Registrar", "Cupones")
                                </li>
                                <li class="submenu-item ">
                                    @Html.ActionLink("Listar cupones", "ListarCupones", "Cupones")
                                </li>
                            </ul>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a class='sidebar-link'>
                                <i class="fas fa-calendar-check"></i>
                                <span>Citas</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    @Html.ActionLink("Citas registradas", "CitasLaboratorio", "Citas")
                                </li>
                            </ul>
                        </li>

                        <li class="sidebar-item  has-sub">
                            <a class='sidebar-link'>
                                <i class="fas fa-user-cog"></i>
                                <span>Perfil</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    @Html.ActionLink("Actualizar perfil", "ActualizarProveedor", "Proveedor")
                                </li>
                                
                            </ul>
                        </li>                    

                        <li class="sidebar-item active">
                            <a href="@Url.Action("Index", "Home", new { itemId = 1 })" class="sidebar-link">
                                <i class="fas fa-door-open m-lg-1"></i>
                                <span>Volver Al Inicio</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
    </section>

    <script src="~/Scripts/dashboard.js"></script>
</body>
</html>