WebUI/Models/ViewModel/RecoveryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebUI.Models.ViewModel
{
    public class RecoveryViewModel
    {
        //esto va a validar que exista el correo electronico, que sea valido su formato
        [EmailAddress]
        //quiero que sea obligatorio
        [Required]
        public string Email{get; set; }
    }
}

WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{

    public class HomeController : Controller
    {
        string urlDomain = "https://nolimits.azurewebsites.net/";
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Login()
        {
            ViewBag.Message = "Login page.";

            return View();
        }
        public ActionResult Producto()
        {
            ViewBag.Message = "Login page.";

            return View();
        }

        [HttpPost]
        public string EnviarQR (string nom, string id, string lab, string con, string exa, string tel, string email, string dir, string correoUsuario)
        {
            try {
                string EmailOrigen = "nolimitsolutionscr92@gmail.com";
                string Contraseña = "eqqrzaqbhpylvdor";
                string URL = "https://nolimits.azurewebsites.net/ConfirmacionQR/ConfirmacionQR?" +
                    "nom=" + nom + "&" +
                    "id=" + id + "&" +
                    "lab=" + lab + "&" +
                    "con=" + con + "&" +
                    "exa=" + exa + "&" +
                    "tel=" + tel + "&" +
                    "email=" + email + "&" +
                    "dir=" + dir;
                string ContenidoHTML =
                                       // "<script src=\"https://cdn.rawgit.com/davidshimjs/qrcodejs/gh-pages/qrcode.min.js\"></script>"+
                                       // "<script>function generar(){let qrcodeContainer = document.getElementById(\"qrcode\");qrcodeContainer.innerHTML = \"\";new QRCode(qrcodeContainer, '" +URL+"');}</script>"+
                                        "<body>" +
                                        "<div>" +
                                        "<b>Datos de la cita: </b><br/>" +
                                        "<b>Nombre:" + nom + "</b><br/>" +
                                        "<b>Id:" + id + "</b><br/>" +
                                        "<b>Laboratorio:" + lab + "</b><br/>" +
                                        "<b>Fecha:" + con + "</b><br/>" +
                                        "<b>Examen:" + exa + "</b><br/>" +
                                        "<b>Telefono:" + tel + "</b><br/>" +
                                        "<b>Correo:" + email + "</b><br/>" +
                                        "<b>Direccion:" + dir + "</b><br/>" +
                                        "</div>" +
                                        "<a href=\""+URL+"\">Confirmar Cita</a>"+
                                        //"<div id='qrcode'></div>" +
                                        "</body>";
                MailMessage oMailMessage = new MailMessage(EmailOrigen, correoUsuario, "Confirmación de su cita", ContenidoHTML );
                oMailMessage.IsBodyHtml = true;

                SmtpClient oSmtpClient = new SmtpClient("smtp.gmail.com");
                oSmtpClient.EnableSsl = true;
                oSmtpClient.UseDefaultCredentials = false;
                oSmtpClient.Port = 587;
                oSmtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
                oSmtpClient.Credentials = new System.Net.NetworkCredential(EmailOrigen, Contraseña);

                oSmtpClient.Send(oMailMessage);

                oSmtpClient.Dispose();

                return "enviado";

            } catch (Exception ex) {

                return ex.Message;
            }
            
        }

        [HttpGet]
        public ActionResult StartRecovery()
        {
            Models.ViewModel.RecoveryViewModel model = new Models.ViewModel.RecoveryViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult StartRecovery(Models.ViewModel.RecoveryViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                string token = GetSha256(Guid.NewGuid().ToString());

                using (Models.Entities db = new Models.Entities())
                {
                    //aqui valido que el correo del usuario en data sea igual al que traigo en mi model
                    var oUser = db.usuarios.Where(d => d.email == model.Email).FirstOrDefault();
                    if (oUser != null)
                    {
                        // aqui editamos el token
                        oUser.token_recovery = token;
                        db.Entry(oUser).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();

                        //enviar mail
                        
                        SendEmail(oUser.email, token);

                    }
                }
                ViewBag.Message = "Se ha enviado un enlace a su correo Electrónico";
                return View();
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        //cuando recibo un correo de parte de mi sistema e ingreso new password
        //el recovery va a recibir el token
        [HttpGet]
        public ActionResult Recovery(string token)
        {
            Models.ViewModel.RecoveryPasswordViewModel model = new Models.ViewModel.RecoveryPasswordViewModel();
            model.token = token;
            using (Models.Entities db = new Models.Entities())
            {

                //aqui hacemos que el token una vez utilizado sea null y ya no se pueda recuperar contraseña con el mismo token
                if (model.token == null || model.token.Trim().Equals(""))
                {
                    return View("Login");
                }
                //en caso que el token exista, va a ir al usuario a buscarlo
                var oUser = db.usuarios.Where(d => d.token_recovery == model.token).FirstOrDefault();
                if (oUser == null)
                {
                    ViewBag.Error = "Token Expirado";
                    return View("Login");
                }
            }

            return View(model);
        }
        [HttpPost]
        public ActionResult Recovery(Models.ViewModel.RecoveryPasswordViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                using (Models.Entities db = new Models.Entities())
                {
                    var oUser = db.usuarios.Where(d => d.token_recovery == model.token).FirstOrDefault();

                    if (oUser != null)
                    {
                        oUser.password = model.Password;
                        oUser.token_recovery = null;
                        db.Entry(oUser).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();

                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }


           
            return View("Login");
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index");
        }


        [HttpPost]
        public string SendFactura(string destino, int clave, string detalle, string descuento, float impuesto, float total, string fecha)
        {
            SendEmailFactura(destino, clave, detalle, descuento, impuesto, total, fecha);
            return "success";
        }

        [HttpPost]
        public string SendResultado(string destino, string descripcion, string evaluacion, int idCita)
        {
            SendEmailResultado(destino, descripcion, evaluacion, idCita);
            return "success";
        }


        #region Helpers
        private string GetSha256(string str)
        {
            SHA256 sha256 = SHA256Managed.Create();
            ASCIIEncoding encoding = new ASCIIEncoding();
            byte[] stream = null;
            StringBuilder sb = new StringBuilder();
            stream = sha256.ComputeHash(encoding.GetBytes(str));
            for (int i = 0; i < stream.Length; i++) sb.AppendFormat("{0:x2}", stream[i]);
            return sb.ToString();
        }

        //aqui envio el correow

        private void SendEmail(string EmailDestino, string token)
        {
            string EmailOrigen = "nolimitsolutionscr92@gmail.com"; 
            string Contraseña = "eqqrzaqbhpylvdor";
            string url = urlDomain + "Home/Recovery/?token=" + token;
            MailMessage oMailMessage = new MailMessage(EmailOrigen, EmailDestino, "Recuperacion de contraseña",
                "<p>Recibimos una solicitud para restablecer la contraseña" +
                "de su cuenta NoLimitsApp, utilice el siguiente enlace" +
                "de autenticación para restablecer su contraseña.</p><br>" +
                "<a href='" + url + "' >Click para recuperar</a>");
            oMailMessage.IsBodyHtml = true;

            SmtpClient oSmtpClient = new SmtpClient("smtp.gmail.com");
            oSmtpClient.EnableSsl = true;
            oSmtpClient.UseDefaultCredentials = false;
            oSmtpClient.Port = 587;
            oSmtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
            oSmtpClient.Credentials = new System.Net.NetworkCredential(EmailOrigen, Contraseña);

            oSmtpClient.Send(oMailMessage);

            oSmtpClient.Dispose();

        }

WebUI/Controllers/PacienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class PacienteController : Controller
    {
        public ActionResult Dashboard()
        {
            return View();
        }
        public ActionResult Listar()
        {
            return View();
        }
        public ActionResult Facturas()
        {
            return View();
        }

        public ActionResult ActualizarUsuario()
        {
            return View();
        }
    }
}

WebUI/Controllers/ProveedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class ProveedorController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Listar()
        {
            return View();
        }

        public ActionResult ActualizarProveedor()
        {
            return View();
        }

        public ActionResult Suscripcion()
        {
            return View();
        }
    }
}

WebUI/Controllers/RegistroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class RegistroController : Controller
    {
        // GET: Registro
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Paciente()
        {
            ViewBag.Message = "Registro Usuarios";

            return View();
        }

        public ActionResult Proveedor()
        {
            ViewBag.Message = "Registro Proveedor";
            return View();
        }

        public ActionResult Laboratorio()
        {
            ViewBag.Message = "Registro Laboratorios";

            return View();
        }
        public ActionResult VerificacionOTP()
        {
            ViewBag.Message = "Verificacion OTP";

            return View();
        }
    }
}

WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div class="container">
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</div>

WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<div class="container">
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</div>

WebUI/Views/Home/Login.cshtml
@{ 
    ViewBag.Title = "Login";
}


<div style="color: red">
    @ViewBag.Error
</div>
<div class="login-wrapper">

    <div class="ltn__login-area pb-65">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title-area text-center">
                        <h1 class="section-title">Inicio Sesión</h1>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="account-login-inner">
                        <div class="ltn__form-box contact-form-box">
                            <input type="text" name="correo" placeholder="Correo Electrónico*" id="txt_correo">
                            <input type="password" name="password" placeholder="Password*" id="txt_password">
                            <div class="btn-wrapper mt-0">
                                <button class="theme-btn-1 btn btn-block" type="submit" id="iniciarSesion" onclick="Login()">INICIAR SESIÓN</button>
                            </div>
                            <div class="go-to-btn mt-20">
                                @Html.ActionLink("¿Olvidaste tu contraseña?", "/StartRecovery")     
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="account-create text-center pt-50">
                        <h4>Registrarse</h4>
                        <p>
                            Presione el botón de registrarse <br>
                            para comenzar a utilizar nuestros servicios.
                        </p>
                        <div class="btn-wrapper">
                            <a href="/Home/Producto#Registrarse" class="theme-btn-1 btn black-btn">Registrarse</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="~/Assets/Scripts/LoginValidation.js"></script>

WebUI/Views/Home/Producto.cshtml
<div class="body-wrapper">

    <div class="ltn__utilize-overlay"></div>
    <div class="ltn__breadcrumb-area text-left bg-overlay-white-30 bg-image " data-bs-bg="/Assets/img/ImgLab.png">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ltn__breadcrumb-inner">
                        <h1 class="page-title">Nuestro Producto</h1>
                        <div class="ltn__breadcrumb-list">
                            <ul>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="ltn__about-us-area pb-115">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 align-self-center">
                    <div class="about-us-img-wrap ltn__img-shape-left  about-img-left">
                        <img src="~/Assets/img/Labimagen2.png" alt="Image">
                    </div>
                </div>
                <div class="col-lg-7 align-self-center">
                    <div class="about-us-info-wrap">
                        <div class="section-title-area ltn__section-title-2--- mb-20">
                            <h6 class="section-subtitle section-subtitle-2 ltn__secondary-color">Sobre Nosotros</h6>
                            <h1 class="section-title">El mejor servicio de suscripción de laboratorios en el país</h1>
                            <p>
                                Somos una empresa que se dedica a ofrecer un servicio de suscripción mensual a laboratorios, con el objetivo de que estos puedan listar sus exámenes para que los clientes puedan adquirirlos. Contamos con los mejores laboratorios y equipamiento para que nuestros clientes obtengan los resultados que necesitan.


                            </p>
                        </div>
                        <div class="about-us-info-wrap-inner about-us-info-devide---">
                            <p>
                                Nuestro objetivo es simplificar el proceso de adquisición de exámenes médicos, para que nuestros clientes puedan obtener los resultados que necesitan de manera rápida y eficiente. contamos con un equipo de profesionales altamente capacitados que estarán encantados de atenderte.
                            </p>
                        </div>
                        <div class="btn-wrapper animated">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="Registrarse" class="ltn__service-area section-bg-1 pt-115 pb-70">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title-area ltn__section-title-2--- text-center">
                        <h6 class="section-subtitle section-subtitle-2 ltn__secondary-color">Nuestro Servicios</h6>
                        <h1 class="section-title">Nuestros Servicios Principales</h1>
                    </div>
                </div>
            </div>
            <div class="row  justify-content-center">
                <div class="col-lg-6 col-sm-6 col-12">
                    <div class="ltn__feature-item ltn__feature-item-6 text-center bg-white  box-shadow-1">
                        <div class="ltn__feature-icon">
                            <span><i class="flaticon-stethoscope"></i></span>

                        </div>
                        <div class="ltn__feature-info">
                            <h3> @Html.ActionLink("Regístrate Como Proveedor", "Proveedor", "Registro")</h3>
                            <p>Regístrate como proveedor y podrás listar tus exámenes para que los clientes puedan adquirirlos.</p>

                        </div>
                        <div class="btn-wrapper animated">
                            <span class="theme-btn-1 btn btn-effect-1 text-uppercase">
                                @Html.ActionLink("Regístrate", "Proveedor", "Registro")
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-6 col-12">
                    <div class="ltn__feature-item ltn__feature-item-6 text-center bg-white  box-shadow-1">
                        <div class="ltn__feature-icon">
                            <span><i class="fas fa-user"></i></span>

                        </div>
                        <div class="ltn__feature-info">
                            <h3><h3> @Html.ActionLink("Regístrate Como Paciente", "Proveedor", "Registro")</h3></h3>
                            <p>Regístrate como paciente y podrás buscar y comprar los exámenes que necesitas de manera rápida y eficiente.</p>

                        </div>
                        <div class="btn-wrapper animated">
                            <span class="theme-btn-1 btn btn-effect-1 text-uppercase">
                                @Html.ActionLink("Regístrate", "Paciente", "Registro")
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 col-12">
                    <div class="ltn__feature-item ltn__feature-item-6 text-center bg-white  box-shadow-1">
                        <div class="ltn__feature-icon">
                            <span><i class="fas fa-search"></i></span>

                        </div>
                        <div class="ltn__feature-info">
                            <h3><a>Busqueda de Laboratorios</a></h3>
                            <p>Ofrecemos diversos laboratorios alrededor del país para que puedas encontrar el que mejor te guste.</p>

                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 col-12">
                    <div class="ltn__feature-item ltn__feature-item-6 text-center bg-white  box-shadow-1">
                        <div class="ltn__feature-icon">
                            <span><i class="flaticon-mortarboard"></i></span>

                        </div>
                        <div class="ltn__feature-info">
                            <h3><a>Venta de Examenes</a></h3>
                            <p>Venta de exámenes: ofrecemos una amplia variedad de exámenes para que puedas encontrar el que necesitas.</p>

                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 col-12">
                    <div class="ltn__feature-item ltn__feature-item-6 text-center bg-white  box-shadow-1">
                        <div class="ltn__feature-icon">
                            <span><i class="flaticon-secure"></i></span>

                        </div>
                        <div class="ltn__feature-info">
                            <h3><a>Profesionales capacitados</a></h3>
                            <p>Nuestro equipo de profesionales está altamente capacitado para ofrecerte el mejor servicio posible.</p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="ltn__blog-area pt-120 pb-70">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title-area ltn__section-title-2 text-center">
                        <h1 class="section-title">Ventajas<span></span></h1>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-4 col-sm-6 col-12">
                    <div class="ltn__feature-item ltn__feature-item-7">
                        <div class="ltn__feature-icon-title">
                            <div class="ltn__feature-icon">

                                <span><i class="fas fa-hand-holding-medical"></i> </span>
                            </div>
                            <h3><a>Resultados</a></h3>
                        </div>
                        <div class="ltn__feature-info">
                            <p>Contamos con los mejores laboratorios y equipamiento para que nuestros clientes obtengan los resultados que necesitan.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 col-12">
                    <div class="ltn__feature-item ltn__feature-item-7">
                        <div class="ltn__feature-icon-title">
                            <div class="ltn__feature-icon">

                                <span><i class="fas fa-vial"></i></span>
                            </div>
                            <h3><a>Simplificacion</a></h3>
                        </div>
                        <div class="ltn__feature-info">
                            <p>Nuestro objetivo es simplificar el proceso de adquisición de exámenes médicos para otorgar facilidad a nuestros clientes.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 col-12">
                    <div class="ltn__feature-item ltn__feature-item-7">
                        <div class="ltn__feature-icon-title">
                            <div class="ltn__feature-icon">

                                <span><i class="fas fa-user-tie"></i></span>
                            </div>
                            <h3><a>Capacidad</a></h3>
                        </div>
                        <div class="ltn__feature-info">
                            <p>Contamos con un equipo de profesionales altamente capacitados que estarán encantados de atenderte.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title-area ltn__section-title-2 text-center">
                        <h6 class="section-title"> Desventajas </h6>

                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-4 col-sm-6 col-12">
                    <div class="ltn__feature-item ltn__feature-item-7">
                        <div class="ltn__feature-icon-title">
                            <div class="ltn__feature-icon">

                                <span><i class="fas fa-money-bill-wave"></i></span>
                            </div>
                            <h3><a>Precio</a></h3>
                        </div>
                        <div class="ltn__feature-info">
                            <p>El costo del servicio mensual puede ser un poco elevado para algunos clientes.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 col-12">
                    <div class="ltn__feature-item ltn__feature-item-7">
                        <div class="ltn__feature-icon-title">
                            <div class="ltn__feature-icon">

                                <span><i class="fas fa-microscope"></i> </span>
                            </div>
                            <h3><a>Servicios</a></h3>
                        </div>
                        <div class="ltn__feature-info">
                            <p>El servicio solo está disponible únicamente para laboratorios.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 col-12">
                    <div class="ltn__feature-item ltn__feature-item-7">
                        <div class="ltn__feature-icon-title">
                            <div class="ltn__feature-icon">

                                <span><i class="fas fa-layer-group"></i></span>
                            </div>
                            <h3><a>Disponibilidad</a></h3>
                        </div>
                        <div class="ltn__feature-info">
                            <p>No podemos garantizar la disponibilidad de todos los exámenes en todos los laboratorios.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


</div>
<script src="~/Scripts/PluginsVicodinComponents.js"></script>
<script src="~/Scripts/MainVicodinComponents.js"></script>

WebUI/Views/Home/Recovery.cshtml
@model WebUI.Models.ViewModel.RecoveryPasswordViewModel
@{
    ViewBag.Title = "Recovery";
}
<div class="row">
    <div class="col-md-6 offset-3">
        <form action="@Url.Content("Recovery")" method="post">
            @Html.HiddenFor(d=> d.token)
            <div class="account-login-inner">
                <div class="ltn__form-box contact-form-box">
                    <label>Escribe tu nueva contraseña.</label>
                    @Html.PasswordFor(d => d.Password, new { @class = "ltn__form-box contact-form-box" })
                    @Html.ValidationMessageFor(d => d.Password, null, new { style = "color: red" })

                    <label>Vuelve a escribir tu contraseña.</label>
                    @Html.PasswordFor(d => d.Password2, new { @class = "ltn__form-box contact-form-box" })
                    @Html.ValidationMessageFor(d => d.Password2, null, new { style = "color: red" })
                    <div class="btn-wrapper d-grid gap-2 col-6 mx-auto">
                        <button class="theme-btn-1 btn reverse-color btn-block">Recuperar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

WebUI/Views/Home/Servicios.cshtml
@{
    ViewBag.Title = "Servicios";
}

<div class="container">
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</div>

WebUI/Views/Home/StartRecovery.cshtml
@model WebUI.Models.ViewModel.RecoveryViewModel
@{
    ViewBag.Title = "StartRecovery";
}

<div class="row">
    <div class="col-md-6 offset-3">
        <form action="@Url.Content("StartRecovery")" method="post">
            <div class="account-login-inner">
                <div class="ltn__form-box contact-form-box">
                    <label>Escribe tu correo electrónico.</label>
                    @Html.TextBoxFor(d => d.Email, null, new { @class = "ltn__form-box contact-form-box" })
                    @Html.ValidationMessageFor(d => d.Email, null, new { style = "color: red" })
                    <div class="btn-wrapper d-grid gap-2 col-6 mx-auto">
                        <button class="theme-btn-1 btn reverse-color btn-block">Recuperar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>