WebUI/Controllers/LaboratorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class LaboratorioController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Laboratorios Registrados";

            return View();
        }
        public ActionResult Registrar()
        {
            return View();
        }
        public ActionResult Dashboard()
        {
            return View();
        }
        public ActionResult Informacion()
        {
            return View();
        }
        public ActionResult Examenes()
        {
            return View();
        }
        public ActionResult EditarLaboratorio()
        {
            return View();
        }
    }
}

WebUI/Controllers/ProveedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class ProveedorController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Listar()
        {
            return View();
        }

        public ActionResult ActualizarProveedor()
        {
            return View();
        }

        public ActionResult Suscripcion()
        {
            return View();
        }
    }
}

WebUI/Views/Proveedor/ActualizarProveedor.cshtml
@{
    ViewBag.Title = "Actualizar Proveedor";
    

}
<link href="~/Assets/css/RegistroPaciente.css" rel="stylesheet" />

<div class="container">
    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div >
                    <h3>Perfil Proveedor</h3>
                    
                </div>
                <div class="btn-wrapper d-grid gap-2 col-2 mb-30 ">
                    <button onclick="history.back()" class="theme-btn-1 btn reverse-color btn-block" type="submit">Regresar</button>
                </div>
            </div>
        </div>

        <section id="multiple-column-form">
            <div class="row match-height">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Actualización de perfil | Información personal</h4>
                        </div>
                        <div class="card-content">
                            <div id="form" class="card-body">

                                <form id="form" class="requires-validation" novalidate action="#">

                                    <div class="row">
                                        <div class="col-md-6">
                                            <h6>Nombre completo</h6>
                                            <div class="input-control">
                                                <input type="text" name="ltn__name" class="form-control" id="txtNombreCompleto" aria-describedby="inputGroupPrepend" required>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <h6>Identificación</h6>
                                            <div class="input-control">
                                                <input type="text" name="ltn__lastname" class="form-control" id="txtIdentificacion" aria-describedby="inputGroupPrepend" disabled="disabled" required>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <h6>Correo Electónico</h6>
                                            <div class="input-control">
                                                <input type="email" name="ltn__email" class="form-control" id="txtCorreo" aria-describedby="inputGroupPrepend" required>
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <h6>Célular</h6>
                                            <div class="input-control">
                                                <input type="text" name="ltn__phone" class="form-control" id="txtTelefono" aria-describedby="inputGroupPrepend" required>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="col-md-3">
                                            <h6>Provincia</h6>
                                            <div class="input-control">
                                                <input type="text" id="txtProvincia" class="form-control" required>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <h6>Cantón</h6>
                                            <div class="input-control">
                                                <input type="text" id="txtCanton" class="form-control" required>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <h6>Distrito</h6>
                                            <div class="input-control">
                                                <input type="text" id="txtDistrito" class="form-control" required>
                                            </div>
                                        </div>



                                    </div>
                                    <div class="row">
                                        <h6>Dirección</h6>
                                        <div class="input-item input-item-textarea ">
                                            <textarea name="ltn__message" class="form-control" id="txtDescripcion" aria-describedby="inputGroupPrepend" required></textarea>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <h6>Contraseña</h6>
                                        <div class="input-control">
                                            <input type="password" id="txtPassword">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <h6>Confirmar Contraseña</h6>
                                        <div class="input-control">
                                            <input type="password" id="txtConfirmarPassword">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="card text-center col-6 mx-auto" style="width: 18rem;">
                                            <img src="~/Assets/img/usuariodefault.jpg" class="card-img-top" alt="" id="user-photo">
                                            <div class="card-body">
                                                <p class="card-text">Seleccione su foto de perfil</p>
                                                <button id="btn-foto" type="button" class="btn theme-btn-1">Subir Imagen</button>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="btn-wrapper d-grid gap-2 col-6 mx-auto">
                                        <button class="theme-btn-1 btn reverse-color btn-block" type="submit">Actualizar</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>



</div>


<script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="~/Assets/Scripts/ServicioFoto.js"></script>
<script src="~/Assets/Scripts/ActualizarPaciente.js"></script>

WebUI/Views/Proveedor/Index.cshtml
@{
    ViewBag.Title = "Mi cuenta";
    
}

<div class="ltn__breadcrumb-area text-left bg-overlay-white-30 bg-image " data-bs-bg="img/bg/14.jpg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="ltn__breadcrumb-inner">
                    <h1 class="page-title">Administrar perfil</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="liton__wishlist-area pb-70">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="ltn__product-tab-area">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="ltn__tab-menu-list mb-50">
                                    <div class="nav">
                                        <a class="active show" data-bs-toggle="tab" href="#liton_tab_1_1">Laboratorios <i class="fas fa-home"></i></a>
                                        @Html.ActionLink("Actualizar perfil", "ActualizarProveedor", "Proveedor")
                                        @Html.ActionLink("Cerrar sesión", "Logout", "Home")
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-8">
                                <div class="tab-content">
                                    <div class="tab-pane fade active show" id="liton_tab_1_1">
                                        <button class="theme-btn-1 btn reverse-color btn-block  mb-10" type="button">@Html.ActionLink("Registrar laboratorio", "Registrar", "Laboratorio")</button>
                                        <div class="ltn__myaccount-tab-content-inner">
                                            <table id="tbl-labs" class="display" style="width:100%">
                                                <thead>
                                                    <tr>
                                                        <th>Nombre del laboratorio</th>
                                                        <th class="id-lab">Identificación</th>
                                                        <th>Administrar</th>
                                                        <th>Eliminar</th>
                                                        <th>Editar</th>
                                                    </tr>
                                                </thead>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="liton_tab_1_2">
                                        <div class="ltn__myaccount-tab-content-inner">
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th>Fecha de registro</th>
                                                        <th>Nombre del laboratorio</th>
                                                        <th>Administrar</th>
                                                        <th>Eliminar</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="~/Assets/Scripts/AdministrarPerfilProveedor.js"></script>

WebUI/Views/Proveedor/Listar.cshtml
@{
    ViewBag.Title = "Listar";
    Layout = "~/Views/Shared/Layouts/DashboardAdmin.cshtml";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Proveedores</h3>
                <p class="text-subtitle text-muted">..</p>
            </div>
        </div>
    </div>

    <section id="multiple-column-form">
        <div class="row match-height">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Proveedores registrados</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">

                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Fecha de registro</th>
                                            <th>Nombre</th>
                                            <th>Laboratorios registrados</th>
                                            <th>Eliminar</th>
                                            <th>Editar informacion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

WebUI/Views/Proveedor/Suscripcion.cshtml
@{
    ViewBag.Title = "Suscripción";
}


<div class="mt-100 ltn__our-history-area pb-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="ltn__our-history-inner">
                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="liton_tab_2_2">
                            <div class="ltn__product-tab-content-inner">
                                <div class="row">
                                    <div class="col-lg-6 align-self-center">
                                        <div class="about-us-img-wrap about-img-left">
                                            <img src="/Assets/img/who.jpg" alt="Image">
                                            <div class="ltn__history-icon">
                                                <i class="icon-award"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 align-self-center">
                                        <div class="about-us-info-wrap">
                                            <div class="section-title-area ltn__section-title-2--- text-center---">
                                                <h6 class="section-subtitle section-subtitle-2 ltn__secondary-color">Felicitaciones</h6>
                                                <h1 class="section-title"> Suscripción completada con exito! </h1>
                                                <p>Ahora puedes registrar laboratorios y potenciar tus ventas con NoLimits Solutions</p>
                                            </div>

                                            <p>Es momento de hacer crecer tu negocio</p>
                                            <div class="btn-wrapper animated">
                                                <a href="/Proveedor" class="theme-btn-1 btn btn-effect-1 text-uppercase">Regresar</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="~/Assets/Scripts/ValidarSuscripcionProveedor.js"></script>